# Importing the necessary libraries:

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Reading the csv file:

In [2]:
df=pd.read_csv('Advertising.csv')

In [3]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

# Separating X and y values:

In [4]:
X=df.drop('sales',axis=1)
y=df['sales']

# Let's import the PolynomialFeatures library:

In [5]:
from sklearn.preprocessing import PolynomialFeatures

# Creating the the object or instance of  Polynomial library:

In [6]:
polynomial_converter=PolynomialFeatures(degree=3,include_bias=False)

# Now fitting & transforming the X:

In [7]:
poly_features=polynomial_converter.fit_transform(X)

# To check the shape of poly_features :

In [8]:
poly_features.shape

(200, 19)

# Importing the train_test_split library:

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [12]:
X_train

array([[1.93200000e+02, 1.84000000e+01, 6.57000000e+01, ...,
        2.22433920e+04, 7.94234160e+04, 2.83593393e+05],
       [2.87600000e+02, 4.30000000e+01, 7.18000000e+01, ...,
        1.32758200e+05, 2.21675320e+05, 3.70146232e+05],
       [8.02000000e+01, 0.00000000e+00, 9.20000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 7.78688000e+02],
       ...,
       [2.39800000e+02, 4.10000000e+00, 3.69000000e+01, ...,
        6.20289000e+02, 5.58260100e+03, 5.02434090e+04],
       [2.14700000e+02, 2.40000000e+01, 4.00000000e+00, ...,
        2.30400000e+03, 3.84000000e+02, 6.40000000e+01],
       [1.63300000e+02, 3.16000000e+01, 5.29000000e+01, ...,
        5.28238240e+04, 8.84297560e+04, 1.48035889e+05]])

# Importing the StandardScaler library:

In [13]:
from sklearn.preprocessing import StandardScaler

# Creating the object:

In [14]:
scaler=StandardScaler()

# Then fitting the scaler object:

In [15]:
scaler.fit(X_train)

StandardScaler()

# Then transform X_train & X_test:

In [16]:
scaled_X_train=scaler.transform(X_train)

In [17]:
scaled_X_test=scaler.transform(X_test)

# Now let's compare the first value of scaled_X_train & poly_features:

In [21]:
scaled_X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [22]:
poly_features[0]

array([2.30100000e+02, 3.78000000e+01, 6.92000000e+01, 5.29460100e+04,
       8.69778000e+03, 1.59229200e+04, 1.42884000e+03, 2.61576000e+03,
       4.78864000e+03, 1.21828769e+07, 2.00135918e+06, 3.66386389e+06,
       3.28776084e+05, 6.01886376e+05, 1.10186606e+06, 5.40101520e+04,
       9.88757280e+04, 1.81010592e+05, 3.31373888e+05])

# Let's import the Ridge library:

In [23]:
from sklearn.linear_model import Ridge

In [24]:
ridge_model=Ridge(alpha=10)

In [25]:
ridge_model.fit(scaled_X_train,y_train)

Ridge(alpha=10)

# Now let's get the prediction from ridge_model:

In [26]:
test_predictions=ridge_model.predict(scaled_X_test)

# Now let's check the mean_absolute_error & mean_squared_error:

In [27]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [28]:
MAE=mean_absolute_error(y_test,test_predictions)

In [29]:
MAE

0.5774404204714166

In [30]:
RMSE=np.sqrt(mean_squared_error(y_test,test_predictions))

In [31]:
RMSE

0.8946386461319675

# Let's import the RidgeCV library and create the object and fit it:

In [32]:
from sklearn.linear_model import RidgeCV

In [36]:
ridge_cv_model=RidgeCV(alphas=(0.1,1.0,10.0),scoring='neg_mean_absolute_error')

In [37]:
ridge_cv_model.fit(scaled_X_train,y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), scoring='neg_mean_absolute_error')

In [38]:
ridge_cv_model.alpha_

0.1

# To get the SCORERS:

In [39]:
from sklearn.metrics import SCORERS

In [40]:
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_weighted'])

# Now let's get the prediction from ridge_cv_model for the scaled_X_test:

In [41]:
test_predictions=ridge_cv_model.predict(scaled_X_test)

# Now let's check the mean_absolute_error & mean_squared_error:

In [42]:
MAE=mean_absolute_error(y_test,test_predictions)

In [43]:
MAE

0.42737748843249934

In [44]:
RMSE=np.sqrt(mean_squared_error(y_test,test_predictions))

In [45]:
RMSE

0.6180719926923581

# Let's import the LassoCV library , create the object and fit it:

In [46]:
from sklearn.linear_model import LassoCV

In [65]:
lasso_cv_model=LassoCV(eps=0.001,n_alphas=100,cv=5,max_iter=100000)

In [66]:
lasso_cv_model.fit(scaled_X_train,y_train)

LassoCV(cv=5, max_iter=100000)

# To get the best alpha:

In [67]:
lasso_cv_model.alpha_

0.004943070909225827

# Now let's get the prediction from lasso_cv_model:

In [68]:
test_predictions=lasso_cv_model.predict(scaled_X_test)

# Now let's check the mean_absolute_error & mean_squared_error:

In [69]:
MAE=mean_absolute_error(y_test,test_predictions)

In [70]:
MAE

0.43350346185900673

In [71]:
RMSE=np.sqrt(mean_squared_error(y_test,test_predictions))

In [72]:
RMSE

0.6063140748984029

# According to the result, Ridge performs better than Lasso.

# Let's import the ElasticNetCV library, create model & fit it:

In [55]:
from sklearn.linear_model import ElasticNetCV

In [57]:
elastic_model=ElasticNetCV(l1_ratio=[.1,.5,.7,.9,.95,.99,1],eps=0.001,n_alphas=100,max_iter=100000)

In [58]:
elastic_model.fit(scaled_X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=100000)

# To get l1_ratio values:

In [59]:
elastic_model.l1_ratio

[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1]

# To get the best l1_ratio:

In [61]:
elastic_model.l1_ratio_

1.0

# To get the best alpha:

In [63]:
elastic_model.alpha_

0.004943070909225827

# It's the same value as lasso best alpha:

In [73]:
lasso_cv_model.alpha_

0.004943070909225827

# Now let's get the prediction from elastic_model:

In [74]:
test_predictions=elastic_model.predict(scaled_X_test)

# Now let's check the mean_absolute_error & mean_squared_error:

In [75]:
MAE=mean_absolute_error(y_test,test_predictions)

In [76]:
MAE

0.43350346185900673

In [77]:
RMSE=np.sqrt(mean_squared_error(y_test,test_predictions))

In [78]:
RMSE

0.6063140748984029

# sama as MAE in lasso